# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: caption.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'caption.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcaption.proto\x12\x07\x63\x61ption\"\x1d\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\":\n\x0f\x43\x61ptionResponse\x12\x0f\n\x07\x63\x61ption\x18\x01 \x01(\t\x12\x16\n\x0einference_time\x18\x02 \x01(\x02\x32Y\n\x13ImageCaptionService\x12\x42\n\x0fGenerateCaption\x12\x15.caption.ImageRequest\x1a\x18.caption.CaptionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'caption_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=26
  _globals['_IMAGEREQUEST']._serialized_end=55
  _globals['_CAPTIONRESPONSE']._serialized_start=57
  _globals['_CAPTIONRESPONSE']._serialized_end=115
  _globals['_IMAGECAPTIONSERVICE']._serialized_start=117
  _globals['_IMAGECAPTIONSERVICE']._serialized_end=206
# @@protoc_insertion_point(module_scope)
