# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stt.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tstt.proto\x12\x03stt\"0\n\nAudioChunk\x12\x0b\n\x03pcm\x18\x01 \x01(\x0c\x12\x15\n\rend_of_stream\x18\x02 \x01(\x08\"9\n\nTranscript\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x1d\n\x04type\x18\x02 \x01(\x0e\x32\x0f.stt.ResultType*$\n\nResultType\x12\x0b\n\x07PARTIAL\x10\x00\x12\t\n\x05\x46INAL\x10\x01\x32\x43\n\x0cSpeechToText\x12\x33\n\x0bStreamAudio\x12\x0f.stt.AudioChunk\x1a\x0f.stt.Transcript(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESULTTYPE']._serialized_start=127
  _globals['_RESULTTYPE']._serialized_end=163
  _globals['_AUDIOCHUNK']._serialized_start=18
  _globals['_AUDIOCHUNK']._serialized_end=66
  _globals['_TRANSCRIPT']._serialized_start=68
  _globals['_TRANSCRIPT']._serialized_end=125
  _globals['_SPEECHTOTEXT']._serialized_start=165
  _globals['_SPEECHTOTEXT']._serialized_end=232
# @@protoc_insertion_point(module_scope)
