# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\x12\x03tts\"1\n\nTTSRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x15\n\rend_of_stream\x18\x02 \x01(\x08\"C\n\x0bTTSResponse\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x32\x42\n\x0cTextToSpeech\x12\x32\n\tStreamTTS\x12\x0f.tts.TTSRequest\x1a\x10.tts.TTSResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TTSREQUEST']._serialized_start=18
  _globals['_TTSREQUEST']._serialized_end=67
  _globals['_TTSRESPONSE']._serialized_start=69
  _globals['_TTSRESPONSE']._serialized_end=136
  _globals['_TEXTTOSPEECH']._serialized_start=138
  _globals['_TEXTTOSPEECH']._serialized_end=204
# @@protoc_insertion_point(module_scope)
