# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ttt.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ttt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tttt.proto\x12\x03tts\"\x1c\n\x0cQueryRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1c\n\x0cTextResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2G\n\x0fRetrieveContext\x12\x34\n\x0cRetrieveText\x12\x11.tts.QueryRequest\x1a\x11.tts.TextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ttt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=18
  _globals['_QUERYREQUEST']._serialized_end=46
  _globals['_TEXTRESPONSE']._serialized_start=48
  _globals['_TEXTRESPONSE']._serialized_end=76
  _globals['_RETRIEVECONTEXT']._serialized_start=78
  _globals['_RETRIEVECONTEXT']._serialized_end=149
# @@protoc_insertion_point(module_scope)
